---
- name: Create appmarbles run script
  template:
    src: "{{ pjroot }}/playbooks/ops/appmarbles/templates/appmarbles.j2"
    dest: "{{ pjroot }}/vars/run/appmarbles.sh"
    mode: +x

- name: Run the appmarbles application
  command: >-
    docker run -d --network {{ NETNAME }} --name appmarbles --hostname appmarbles
    --expose 8080
    -e ORG_NAME={{ CURRENT_ORG }}
    -v /var/run/docker.sock:/var/run/docker.sock
    -v {{ hostroot }}/vars:/vars
    -v {{ hostroot }}/vars/app/:/go/src/github.com/app
    --entrypoint /vars/run/appmarbles.sh
    {{ LANGUAGEENVS['node'] }}
  register: runstates

- name: appmarbles run
  when: runstates.rc != 0
  debug:
    msg: "{{ runstates.stderr_lines }}"
  tags: [print_action]

- name: appmarbles run
  when: runstates.rc == 0
  debug:
    msg: "Application in node completed successfully"
  tags: [print_action]
